2024-07-15 01:49:24,632 INFO    MainThread:62979 [wandb_setup.py:_flush():76] Current SDK version is 0.17.4
2024-07-15 01:49:24,633 INFO    MainThread:62979 [wandb_setup.py:_flush():76] Configure stats pid to 62979
2024-07-15 01:49:24,633 INFO    MainThread:62979 [wandb_setup.py:_flush():76] Loading settings from /Users/weichaozhou/.config/wandb/settings
2024-07-15 01:49:24,633 INFO    MainThread:62979 [wandb_setup.py:_flush():76] Loading settings from /Users/weichaozhou/Workspace/MIT-REALM/ada_cbf/f1tenth_gym/examples/wandb/settings
2024-07-15 01:49:24,633 INFO    MainThread:62979 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'api_key': '***REDACTED***'}
2024-07-15 01:49:24,633 INFO    MainThread:62979 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'ada_cbf/f1tenth_gym/examples/waypoint_follow_sysid.py', 'program_abspath': '/Users/weichaozhou/Workspace/MIT-REALM/ada_cbf/f1tenth_gym/examples/waypoint_follow_sysid.py', 'program': '/Users/weichaozhou/Workspace/MIT-REALM/ada_cbf/f1tenth_gym/examples/waypoint_follow_sysid.py'}
2024-07-15 01:49:24,633 INFO    MainThread:62979 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-07-15 01:49:24,633 INFO    MainThread:62979 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-07-15 01:49:24,633 INFO    MainThread:62979 [wandb_init.py:_log_setup():529] Logging user logs to /Users/weichaozhou/Workspace/MIT-REALM/ada_cbf/f1tenth_gym/examples/wandb/run-20240715_014924-w9kgugwf/logs/debug.log
2024-07-15 01:49:24,633 INFO    MainThread:62979 [wandb_init.py:_log_setup():530] Logging internal logs to /Users/weichaozhou/Workspace/MIT-REALM/ada_cbf/f1tenth_gym/examples/wandb/run-20240715_014924-w9kgugwf/logs/debug-internal.log
2024-07-15 01:49:24,633 INFO    MainThread:62979 [wandb_init.py:init():569] calling init triggers
2024-07-15 01:49:24,633 INFO    MainThread:62979 [wandb_init.py:init():576] wandb.init called with sweep_config: {}
config: {}
2024-07-15 01:49:24,633 INFO    MainThread:62979 [wandb_init.py:init():619] starting backend
2024-07-15 01:49:24,633 INFO    MainThread:62979 [wandb_init.py:init():623] setting up manager
2024-07-15 01:49:24,634 INFO    MainThread:62979 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-07-15 01:49:24,635 INFO    MainThread:62979 [wandb_init.py:init():631] backend started and connected
2024-07-15 01:49:24,638 INFO    MainThread:62979 [wandb_init.py:init():720] updated telemetry
2024-07-15 01:49:24,663 INFO    MainThread:62979 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-07-15 01:49:24,921 ERROR   MainThread:62979 [wandb_init.py:init():779] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-07-15 01:49:24,921 ERROR   MainThread:62979 [wandb_init.py:init():1191] error in wandb.init()
Traceback (most recent call last):
  File "/Users/weichaozhou/.pyenv/versions/3.10.6/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1181, in init
    return wi.init()
  File "/Users/weichaozhou/.pyenv/versions/3.10.6/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 785, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-07-15 01:49:26,121 WARNING MsgRouterThr:62979 [router.py:message_loop():77] message_loop has been closed
